title: Comidad
email: info@comidad.com
description: > 
  Comunidad de comidas.
baseurl: "" 
url: "http://www.comidad.com"
twitter_username: micomidad
github_username:  comidad
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
